print("First Number? ")
firstNumber = input()
print("Second Number? ")
secondNumber = input()
print(f'Total {firstNumber+secondNumber}')
total = int(firstNumber) + int(secondNumber)
totalPrint = str(total)
print("first number + second number equals " + str(total))
print(firstNumber + secondNumber)